### ISSUE TITLE
Make a better CLI report

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Test#40]
So far, atoum's default CLI report says there is x files, y classes, z methods etc. It does not make sense. We must change that for x' test suites, y' test cases, z' assertions etc.

**Comment by jubianchi** [comment]
@Hywan the exact line is like: 

```
Success (224 tests, 1789/1816 methods, 0 void method, 27 skipped methods, 26776 assertions)!
```

atoum does not count files but classes and calls them "tests". Then it report a number of executed method which is correct (where "test cases" would not) : a test method in atoum can be run 0,n times (0 = skipped) :
* if `n === 1` the method is just a plain standalone method but it could contain several cases (using `->assert()` for example)
* if `n > 1` the method may have been run several times because it was fed with a dataset (coming from a provider)

Given that, talking about "test cases" would be wrong because a method can contain several cases and we can't always count them correctly (actually).

BTW, you can easily customize the wording if you want, the only thing to do is create a custom report extending the [`atoum\reports\realtime\cli`](https://github.com/atoum/atoum/blob/master/classes/reports/realtime/cli.php) and change [the result line](https://github.com/atoum/atoum/blob/master/classes/reports/realtime/cli.php#L79-L83)

**Comment by Hywan** [comment]
@jubianchi In the context of Hoa, speaking about a test case is correct. We renamed the prefix to `case_` and the content is atomic to one test case behavior. So no issue.

How can I extend and “inject” it? I guess I need to remove the existing one too?

**Comment by jubianchi** [comment]
@Hywan Ok fine if it OK for you :)

Take a look at this sample configuration file to see how to inject your custom report through the configuration file (`.atoum.php`) : https://github.com/atoum/atoum/blob/master/resources/configurations/runner/santa.php.dist

**Comment by Hywan** [comment]
@jubianchi Great, thanks!

Any volunteer @hoaproject/hoackers?

**Comment by jubianchi** [comment]
@Hywan I will try to provide you a custom report ;)

**Comment by Hywan** [comment]
@jubianchi Thanks!
